name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '33 0 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Run (LCU)
      run: dotnet run --project ./RiotGames.Help2Swagger/RiotGames.Help2Swagger.csproj --no-build --verbosity normal -- lcu ./release/wwwroot/lcu/openapi.json      
      
    - name: Run (RCS)
      run: dotnet run --project ./RiotGames.Help2Swagger/RiotGames.Help2Swagger.csproj --no-build --verbosity normal -- rcs ./release/wwwroot/rcs/openapi.json
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: release/wwwroot
        jekyll: false
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
